CREATE TABLE IF NOT EXISTS api_keys (
    id SERIAL PRIMARY KEY, 
    binance_key TEXT NOT NULL UNIQUE,
    binance_secret TEXT NOT NULL UNIQUE, 
    name TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS ohlc_data 
(
  id SERIAL PRIMARY KEY,
  dt TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  stock_id INTEGER NOT NULL,
  open NUMERIC NOT NULL,
  high NUMERIC NOT NULL,
  low NUMERIC NOT NULL,
  close NUMERIC NOT NULL,
  volume NUMERIC NOT NULL,
  CONSTRAINT fk_stock FOREIGN KEY(stock_id) REFERENCES stock(id)
);

CREATE TABLE IF NOT EXISTS tick_data  
(
  id SERIAL PRIMARY KEY,
  dt TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  stock_id INTEGER NOT NULL,
  bid NUMERIC NOT NULL,
  ask NUMERIC NOT NULL,
  bid_vol NUMERIC,
  ask_vol NUMERIC,
  CONSTRAINT fk_stock FOREIGN KEY(stock_id) REFERENCES stock(id)
);